name: CI_CD_FW

on:
  push:
    branches:
      - main
  workflow_dispatch:
permissions:
  contents: read
  packages: write

jobs:
  use-reusable-workflow:
    uses: SampleProjectDotNet/reusable-workflows/.github/workflows/dotnet-build-test.yml@main
    secrets: inherit

  deploy:
    needs: use-reusable-workflow
    uses: SampleProjectDotNet/reusable-workflows/.github/workflows/publish-to-file-server.yml@main
    secrets: inherit