name: CI_CD_FW

on:
  push:
    branches:
      - main
  workflow_dispatch:
permissions:
  contents: read
  packages: write

jobs:
  build:
    uses: Migracao-NET/pipeline_templates/.github/workflows/build.yml@main
    with:
      enableSonar: true
    secrets: inherit
    
  deploy:
    needs: build
    uses: Migracao-NET/pipeline_templates/.github/workflows/deploy-app.yml@main
    secrets: inherit
